- name: Install Apache apt packages
  apt:
    state : present
    pkg:
        - apache2
        - libapache2-mod-shib  # sp
        - libapache2-mod-php

- name: Remove Default Index file
  file: path=/var/www/html/index.html state=absent

# TODO optional defaults
- name: Remove Default site configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Remove Default-ssl site configuration
  file: path=/etc/apache2/sites-enabled/default-ssl.conf state=absent

- name: Configure HTTPS only listen port
  copy:
    src: roles/apache2_common/files/ports.conf
    dest: /etc/apache2/ports.conf

- name: Disable PHP 7.3 conflicting Apache2 modules
  apache2_module: name={{ item }} state=absent
  with_items:
    - php7.3
    - mpm_worker
    - mpm_prefork
    - mpm_event
  ignore_errors: true

- name: Enable SSL
  command: a2enmod ssl

- name: Enable PHP 7.3
  command: a2enmod php7.3

- name: Restart Apache2
  service: name=apache2 state=restarted enabled=yes
