- name: Install Apache apt packages
  apt:
    state : present
    pkg:
        - apache2
        - libapache2-mod-shib2  # sp
        - libapache2-mod-php

- name: Remove Default Index file
  file: path=/var/www/html/index.html state=absent

# TODO optional defaults
- name: Remove Default site configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Remove Default-ssl site configuration
  file: path=/etc/apache2/sites-enabled/default-ssl.conf state=absent

- name: Configure HTTPS only listen port
  copy:
    src: roles/apache2_common/files/ports.conf
    dest: /etc/apache2/ports.conf

# - name: Install Apache default servers
  # template:
    # src: "roles/apache2/templates/default.conf"
    # dest: /etc/apache2/sites-available/default.conf
  # force: yes

# - name: Install Apache default-ssl servers
  # template:
    # src: "roles/apache2/templates/default-ssl.conf"
    # dest: /etc/apache2/sites-available/default-ssl.conf
  # force: yes

# - name: Enable default-ssl site configuration
  # command: a2ensite default

# - name: Enable default-ssl site configuration
  # command: a2ensite default-ssl

# Apache2 with PHP 7.0 on Debian9 could drive us crazy with something like:
# Considering dependency mpm_prefork for php7.0:
# Considering conflict mpm_event for mpm_prefork:
# Considering conflict mpm_worker for mpm_prefork:
# Enabling module mpm_prefork.
# Considering conflict php5 for php7.0:
# Enabling module php7.0.

- name: Disable PHP 7.3 conflicting Apache2 modules 
  apache2_module: name={{ item }} state=absent
  with_items:
    - php7.3
    # - mpm_worker
    - mpm_prefork
    - mpm_event
  ignore_errors: true

- name: Enable PHP 7.3
  command: a2enmod php7.3

- name: Restart Apache2
  service: name=apache2 state=restarted enabled=yes
