#  SAML2PersistentGenerator on RDBMS
- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.session.StorageService = shibboleth.ClientSessionStorageService'
    replace: 'idp.session.StorageService = shibboleth.JPAStorageService'
    backup: yes

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.consent.StorageService = shibboleth.ClientPersistentStorageService'
    replace: 'idp.consent.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.replayCache.StorageService = shibboleth.StorageService'
    replace: 'idp.replayCache.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.replayCache.StorageService = shibboleth.StorageService'
    replace: 'idp.replayCache.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.artifact.StorageService = shibboleth.StorageService'
    replace: 'idp.artifact.StorageService = shibboleth.JPAStorageService'

- replace:
    path: "{{ idp_path }}/conf/idp.properties"
    regexp: '#idp.artifact.StorageService = shibboleth.StorageService'
    replace: 'idp.artifact.StorageService = shibboleth.JPAStorageService'
